### ISSUE TITLE
Indexed/non-indexed columns in SELECT benchmarks

### ISSUE THREAD

**Issue by bazzilic** [bazzilic/PrismaDB-Benchmark#3]
For SELECT benchmarks, do separate benchmarks for selecting on an indexed column and selecting on a non-indexed column.

For SELECT with JOIN, perform joins on columns that are indexed in both tables and columns that are not indexed on both columns.

**Comment by kyle-nguyennn** [comment]
table can only be indexed if not connected through proxy.

**Comment by bazzilic** [comment]
We will need to add CREATE INDEX queries to our proxy
