### ISSUE TITLE
Increase # of rows in the database

### ISSUE THREAD

**Issue by bazzilic** [bazzilic/PrismaDB-Benchmark#4]
Increase # of rows in the tables used for benchmarking up to half a million (500 000). Consider adding a config parameter of # of rows.

**Comment by kyle-nguyennn** [comment]
- The number of row can be change in configuration file in node "rows".
- When use 500,000, need to wait around 2 minutes to populate the tables.
- If connected to proxy and use 500,000, this error shows up: "Query caused error: The Command Timeout expired before the operation completed." -> I suggest using 100,000 if connected through proxy.

**Comment by bazzilic** [comment]
Do you insert in bulk or one row at a time? It might make sense to insert in batches of 50,000 or 100,000 records.

**Comment by cheziyi** [comment]
Yes it inserts in bulk. One issue I have realised also is if the query is too long (like 100k entries long), parser will crash when parsing.
