### ISSUE TITLE
Doubling step strategy

### ISSUE THREAD

**Issue by bazzilic** [bazzilic/PrismaDB-Benchmark#5]
For RPS measurement use the doubling step strategy.
Start with a small RPS speed (e.g., 1 RPS).
Each step, double it (2, 4, 8, 16, 64, ...)
If current speed `v` is too high, reduce/increase it by `v/4`, then by `v/8`, then by `v/16` etc until we have a stable max RPS.

**Comment by cheziyi** [comment]
This works well
